### ISSUE TITLE
The error says: 'GaussianMixture' object has no attribute 'covariances_'. How can I solve this problem please?

### ISSUE THREAD

**Issue by yingzhaozhutiao** [shyam671/Multi-Agent-Diverse-Generative-Adversarial-Networks#1]
The new version of sklearn does not have GMM function, but GaussianMixture function. I directly use GaussianMixture instead of GMM and I get an error. 'X = gmm.sample(200000)' has an error and the error says: 'GaussianMixture' object has no attribute 'covariances_'. How can I solve this problem please?

**Comment by gunnxx** [comment]
I use the following
```
np.random.seed(1)
gmm = GMM(5)
gmm.means_ = np.array([[10], [20], [60], [80], [110]])
gmm.covariances_ = np.array([[[3]], [[3]], [[2]], [[2]], [[1]]]) ** 2
gmm.weights_ = np.array([0.2, 0.2, 0.2, 0.2, 0.2])

X = gmm.sample(200000)[0]
data = X
data = (data - X.min())/(X.max()-X.min())
plt.hist(data, 200000, histtype='stepfilled', alpha=1)
```

**Comment by yingzhaozhutiao** [comment]
Thank you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shyam671/Multi-Agent-Diverse-Generative-Adversarial-Networks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月30日(星期三) 中午1:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shyam671/Multi-Agent-Diverse-Generative-Adversarial-Networks] The error says: 'GaussianMixture' object has no attribute 'covariances_'. How can I solve this problem please? (Issue #1)





 
I use the following
 np.random.seed(1) gmm = GMM(5) gmm.means_ = np.array([[10], [20], [60], [80], [110]]) gmm.covariances_ = np.array([[[3]], [[3]], [[2]], [[2]], [[1]]]) ** 2 gmm.weights_ = np.array([0.2, 0.2, 0.2, 0.2, 0.2]) X = gmm.sample(200000)[0] data = X data = (data - X.min())/(X.max()-X.min()) plt.hist(data, 200000, histtype='stepfilled', alpha=1)
